version: "3" #docker-compose version to use
# service -> container
services:
    # service name
    pexon-app:
        build: pexon-app
        volumes:
            # hostpath:guestpath
            - ./pexon-app/src:/app
        depends_on: 
            - mysqlite

    mysqlite:
        image: nouchka/sqlite3
        stdin_open: true
        tty: true
        ports:
            # hostport:guestport
            - 8080:8080
        volumes:
            - ./pexon-app/db:/root/db
